### ISSUE TITLE
Support custom root route

### ISSUE THREAD

**Issue by bebraw** [tj/serve#21]
Hi,

It would be convenient if it was possible to set up a server so that rather than pointing at / by default, it could point to something else (like /foo). We could call this option -R (--root).

Having this option would make it very easy for me to test certain paths generated by a static generator of mine. I'm not sure if there's an utility beyond that, though.

**Comment by emcniece** [comment]
This issue should be closed!

**Comment by stevemao** [comment]
@bebraw is your problem solved?
