### ISSUE TITLE
Use default terminal color for font.

### ISSUE THREAD

**Issue by trusktr** [tj/serve#51]
Use the default terminal color for the main font, otherwise it looks like this in some terminals (iterm2 in OS X in this case):

![screen shot 2015-01-08 at 10 25 13 pm](https://cloud.githubusercontent.com/assets/297678/5676170/4a51654c-9785-11e4-8e88-eed1d43f55f6.png)

**Comment by stevemao** [comment]
Its using `connect.logger`

**Comment by trusktr** [comment]
@stevemao Then configure, or don't use, connect.logger?

**Comment by stevemao** [comment]
@trusktr the deps this module is using is outdated. The logger is actually changed a while ago. If you wanna help, try bump the deps.
