### ISSUE TITLE
Improper redirection?

### ISSUE THREAD

**Issue by peopledrivemecrazy** [tj/serve#52]
When I go to localhost:3000 it gives me a page like this 
<img src=http://i.imgur.com/5uxer9Z.png><BR><a href=http://i.imgur.com/5uxer9Z.png>http://i.imgur.com/5uxer9Z.png</a>
The pages in them have url like this localhost:3000/\index.htm

**Comment by amio** [comment]
By default, only `index.html` would be served as index.
