### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by gdi2290** [tj/serve#60]
Hi TJ, I'm a fan of `serve`. It doesn't look like it's maintained anymore and would love to adopt the project to clean up/add the features

**Comment by Calvein** [comment]
That's what I did in https://github.com/Calvein/serveur if you're interested.
It's just serve with some pull requests.

**Comment by stevemao** [comment]
@tj can you add maintainers?

**Comment by tj** [comment]
Yea I can add whoever is interested, I just use https://github.com/segmentio/serve but that's all I ever really need haha

**Comment by stevemao** [comment]
Thank you @tj :)
