### ISSUE TITLE
Note in README that this is no longer what `npm serve` installs

### ISSUE THREAD

**Issue by ericsoco** [tj/serve#76]
Had a surprise today, actually a couple, when I `npm install`ed projects with `serve` as a dep, and found the API has changed -- post 2.0 versions now install https://github.com/zeit/serve instead, and that package serves up on a random port by default. Not sure there's much left to do on this repo except change the README, but [here's the thread over on the new repo](https://github.com/zeit/serve/issues/87) describing me stumbling over that change.

**Comment by ericsoco** [comment]
(I'd change the README in a PR, but thought you might want to take different action, so...leaving it up to you @tj & co.)

**Comment by stevemao** [comment]
I didn't know 2.0 is in a new repo. I guess this one will be deprecated then.

**Comment by tj** [comment]
ah yeah they asked me for the name. I'll make a note here
